# -*- coding: utf-8 -*-
"""Sample_Regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X62YLJDpg3dC1tCw_gnm5In9ftqnyi6L
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Step 1: Create a dummy DataFrame
data = {
    "age": np.random.randint(25, 60, 100),
    "education": np.random.randint(1, 5, 100),  # Assume education level 1-4
    "experience": np.random.randint(1, 35, 100),
    "salary": np.random.randint(30000, 150000, 100)  # Target variable
}

df = pd.DataFrame(data)

print(df)

# Step 2: Split data into features and target variable
X = df[["age", "education", "experience"]]
y = df["salary"]

# Step 3: Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Train a linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 5: Save the model as a .pkl file
with open("salary_regressor.pkl", "wb") as file:
    pickle.dump(model, file)